version: "3.2"

services:

  api-tools-api:
    image: clarketm/tinyurl-be
    restart: "always"
    build:
      context: ./be/
      args:
        ROOT_DIR: $ROOT_DIR
    command: wait-for-it --service redis:$REDIS_MASTER_SERVICE_PORT --timeout 0 -- make -C be start
    ports:
    - 80:$BE_PORT
    environment:
    - REDIS_MASTER_SERVICE_HOST=redis
    depends_on:
    - redis
    networks:
    - local

  redis:
    image: redis
    restart: "always"
    volumes:
    - redis_db_data:/data
    networks:
    - local

volumes:
  redis_db_data:

networks:
  local:
