version: "3.2"

services:

  tinyurl-ui_dev:
    image: clarketm/tinyurl-fe:latest-dev
    restart: always
    build:
      context: ./fe/
      args:
        ROOT_DIR: $ROOT_DIR
    command: yarn start
    ports:
    - $FE_PORT:$FE_PORT
    environment:
    - CI=true
    volumes:
    - ./fe:/$ROOT_DIR
    networks:
    - local

  tinyurl-api_dev:
    image: clarketm/tinyurl-be:latest-dev
    restart: always
    build:
      context: ./be/
      args:
        ROOT_DIR: $ROOT_DIR
    command: wait-for-it --service redis_dev:$REDIS_MASTER_SERVICE_PORT --timeout 0 -- make start-dev
    ports:
    - $BE_PORT:$BE_PORT
    environment:
    - REDIS_MASTER_SERVICE_HOST=redis_dev
    volumes:
    - ./be:/$ROOT_DIR
    depends_on:
    - redis_dev
    networks:
    - local

  redis_dev:
    image: redis
    restart: always
    volumes:
    - redis_db_data_dev:/data
    networks:
    - local

volumes:
  redis_db_data_dev:

networks:
  local:
