version: "3.2"

services:

  tinyurl-ui:
    image: clarketm/tinyurl-fe:latest
    restart: always
    build:
      context: ./fe/
      args:
        ROOT_DIR: $ROOT_DIR
    command: yarn start
    ports:
    - $FE_PORT:$FE_PORT
    volumes:
    - tinyurl-ui_node_modules:/$ROOT_DIR/node_modules
    networks:
    - local

  tinyurl-api:
    image: clarketm/tinyurl-be:latest
    restart: always
    build:
      context: ./be/
      args:
        ROOT_DIR: $ROOT_DIR
    command: wait-for-it --service redis:$REDIS_MASTER_SERVICE_PORT --timeout 0 -- make start
    ports:
    - $BE_PORT:$BE_PORT
    environment:
    - REDIS_MASTER_SERVICE_HOST=redis
    depends_on:
    - redis
    networks:
    - local

  redis:
    image: redis:latest
    restart: always
    volumes:
    - redis_db_data:/data
    networks:
    - local

volumes:
  tinyurl-ui_node_modules:
  redis_db_data:

networks:
  local:
