################################################################################
# tinyurl
################################################################################

replicaCount: 1

image:
  repository: clarketm/tinyurl
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: tinyurl

serviceAccount:
  create: true
  annotations: {}
  name:

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: "selfsigned-issuer"
  hosts:
  - host: tinyurl.travismclarke.com
    paths:
    - /
  tls:
  - secretName: tinyurl-tls
    hosts:
    - tinyurl.travismclarke.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

################################################################################
# redis
################################################################################
redis:
  fullnameOverride: redis
  usePassword: false