#!/usr/bin/env sh

root_dir=$( git rev-parse --show-toplevel )

be_dir="$root_dir/be"
be_files=$( git diff --cached --name-only --diff-filter=ACM "$be_dir" )

if [ -n "$be_files" ]; then
    make -C "$be_dir" format  ; RESULT_1=$?
    make -C "$be_dir" test    ; RESULT_2=$?
    echo "$be_files" | xargs -rd'\n' git add
    [ "$RESULT_1" -eq 0 -a "$RESULT_2" -eq 0 ] && exit 0 || exit 1
fi

fe_dir="$root_dir/fe"
fe_files=$( git diff --cached --name-only --diff-filter=ACM "$fe_dir" )

if [ -n "$fe_files" ]; then
    pushd "$fe_dir"
    yarn prettier  ; RESULT=$?
    popd
    echo "$fe_files" | xargs -rd'\n' git add
    [ "$RESULT" -eq 0 ] && exit 0 || exit 1
fi
