#!/usr/bin/env sh

root_dir=$( git rev-parse --show-toplevel )
target_dir="$root_dir/be"
files=$( git diff --cached --name-only --diff-filter=ACM "$target_dir" )

make -C "$target_dir" format  ; RESULT_1=$?
make -C "$target_dir" test    ; RESULT_2=$?

echo "$files" | xargs -d'\n' git add

[ "$RESULT_1" -eq 0 -a "$RESULT_2" -eq 0 ] && exit 0 || exit 1
